-- =====================================================================
-- TABLE: sentence
-- PURPOSE: Sentences produced by CoreNLP per paragraph, ordered within
--          each paragraph by sentence_idx.
-- WRITES:  corenlp-worker
-- READS:   spacy-llm (for segmentation, plus ±N paragraph context joins)
-- NOTES:   UNIQUE(book_id, paragraph_id, sentence_idx) ensures idempotent
--          inserts on retries; BIGINT PK keeps joins/indexes lean.
-- =====================================================================

CREATE TABLE sentences (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id          UUID   NOT NULL REFERENCES book(id) ON DELETE CASCADE,
  paragraph_id     BIGINT NOT NULL REFERENCES paragraph(id) ON DELETE CASCADE,
  sentence_idx     INT    NOT NULL CHECK (sentence_idx >= 0),  -- order within paragraph
  text             TEXT   NOT NULL,
  char_start       INT,
  char_end         INT,
  status           TEXT   NOT NULL DEFAULT 'READY'
                     CHECK (status IN ('READY','IN_PROGRESS','DONE','FAILED')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (book_id, paragraph_id, sentence_idx)
);

CREATE INDEX idx_sentence_paragraph   ON sentence(paragraph_id, sentence_idx);
CREATE INDEX idx_sentence_book_status ON sentence(book_id, status, sentence_idx);
