-- =====================================================================
-- TABLE: character_alias
-- PURPOSE: Alias forms ("Jim", "Mr. Halpert") for quick resolution.
-- OWNER:   langextract-service / admin UI.
-- =====================================================================
CREATE TABLE IF NOT EXISTS character_alias (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id       UUID NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
  alias              TEXT NOT NULL,
  normalized_alias   TEXT GENERATED ALWAYS AS (
                        lower(regexp_replace(alias, '[^a-z0-9]+', '', 'g'))
                      ) STORED,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (character_id, normalized_alias)
);
CREATE INDEX IF NOT EXISTS idx_char_alias_norm ON character_alias(normalized_alias);
