-- =====================================================================
-- TABLE: sentence_segment
-- PURPOSE: Fine-grained parts of a sentence (dialogue/narrator/internal),
--          with exact spans and speaker/voice metadata used for synthesis.
-- WRITES:  spacy-llm
-- READS:   editor/audio synthesis pipeline
-- NOTES:   UNIQUE(sentence_id, segment_idx) preserves stable order.
--          character_id is optional; fall back to character_name when NULL.
-- =====================================================================

CREATE TABLE sentence_segments (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sentence_id          BIGINT NOT NULL REFERENCES sentence(id) ON DELETE CASCADE,
  segment_idx          INT    NOT NULL CHECK (segment_idx >= 0),  -- order inside sentence

  -- minimal classification
  type                 TEXT CHECK (
                         type IS NULL OR type IN ('dialogue','narrator','internal_dialogue')
                       ),

  -- exact span in sentence.text
  span_start           INT    NOT NULL CHECK (span_start >= 0),
  span_end             INT    NOT NULL CHECK (span_end > span_start),

  -- speaker/voice metadata
  character_id         UUID REFERENCES character(id),   -- nullable
  character_name       TEXT,                             -- free-text if unresolved
  character_gender     TEXT   DEFAULT 'unknown'
                         CHECK (character_gender IN ('male','female','unknown')),
  character_age_group  TEXT   DEFAULT 'unknown'
                         CHECK (character_age_group IN ('child','adult','senior','unknown')),
  prosody              TEXT   DEFAULT 'neutral'
                         CHECK (prosody IN ('neutral','whisper','shout','angry','happy','sad','tense','calm','excited')),
  metadata             JSONB,                            -- extras (accent, scores…)

  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (sentence_id, segment_idx)
);

CREATE INDEX idx_segment_sentence ON sentence_segment(sentence_id, segment_idx);
CREATE INDEX idx_segment_type     ON sentence_segment(type);
CREATE INDEX idx_segment_char     ON sentence_segment(character_name);
