-- =====================================================================
-- TABLE: character_alias
-- PURPOSE: Maps surface forms ("Jim", "Mr. Halpert") to a canonical
--          character. Used by resolver to set sentence_segment.character_id.
-- WRITES:  spacy-llm (resolver) or admin tools
-- READS:   spacy-llm during alias resolution
-- NOTES:   normalized_alias aids robust matching (case/punct insensitive).
-- IDs:     BIGINT identity; rows are internal helper entries.
-- =====================================================================

CREATE TABLE character_alias (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id       UUID NOT NULL REFERENCES character(id) ON DELETE CASCADE,
  alias              TEXT NOT NULL,
  normalized_alias   TEXT GENERATED ALWAYS AS (
                        lower(regexp_replace(alias, '[^a-z0-9]+', '', 'g'))
                      ) STORED,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (character_id, normalized_alias)
);

CREATE INDEX idx_char_alias_norm ON character_alias(normalized_alias);
