# Cloud specific configurations
server:
  port: 80

logging:
  level:
    root: WARN

app:
  mandatory-property: "cloud" # This is a mandatory property

# Add cloud-specific configurations here (e.g., database URLs, Kafka brokers, S3 bucket names)